marcas = {
    "Ford": 23,
    "Jetour":24,
    "Opel": 25,
    "Mitsubishi": 26,
    "Maxus": 27,
    "Karry": 28,
    "Kaiyi": 29,
    "Volkswagen":30,
    "Audi":31,
    "Skoda":32,
    "Seat":33,
    "Cupra":34,
    "Suzuki": 17,
    "GWM": 18,
    "Renault": 19,
    "Changan": 20,
    "JAC": 21,
    "Deepal":22,
    "Subaru": 16,
    "Mazda": 15,
    "Omoda-jaecoo": 14,
    "Exeed":13,
    "Fiat":12,
    "Jeep": 11,
    "Opel":10,
    "Hyundai": 9,
    "Lexus": 8,
    "Mg": 7,
    "Chery":6,
    "Ram": 5,
    "Citroen": 4,
    "Peugeot": 3,
    "Nissan": 2,
    "Toyota": 1
    
}